using System;
using Unity.Collections.LowLevel.Unsafe;

namespace Realmar.DataBindings.Converters
{
	public class CastConverter<TFrom, TTo> : IValueConverter<TFrom, TTo>
	{
		public TFrom Convert(TTo to)
		{
			return Cast<TTo, TFrom>(to);
		}

		public TTo Convert(TFrom @from)
		{
			return Cast<TFrom, TTo>(@from);
		}


		private TOut Cast<TIn, TOut>(TIn data)
		{
			// check if data is boxed, if yes then we cannot cast it directly
			if (typeof(TOut).IsValueType)
			{
				// for some reason doubles generated by the UnsafeHelpers are too big or too small sometimes
				// doesnt matter for now, as I just wanted to test the generic converters
				try
				{
					return (TOut) System.Convert.ChangeType(data, typeof(TOut));
				}
				catch
				{
					return default;
				}
			}

			return (TOut) (object) data;
		}
	}
}
